services:
  - type: web
    name: datn-backend
    env: docker
    plan: free
    rootDir: backend
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:sqlserver://datn.ct4sc6oi2i77.ap-southeast-1.rds.amazonaws.com:1433;databaseName=datn;encrypt=true;trustServerCertificate=true
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 8080

  - type: web
    name: datn-core-banking
    env: docker
    plan: free
    rootDir: core-banking-service
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:sqlserver://datn.ct4sc6oi2i77.ap-southeast-1.rds.amazonaws.com:1433;databaseName=core_banking;encrypt=true;trustServerCertificate=true
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 8081

  - type: web
    name: datn-notification
    env: docker
    plan: free
    rootDir: notification-service
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 9821 