services:
  - type: web
    name: datn-backend
    env: docker
    plan: free
    rootDir: backend
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:sqlserver://datn.ct4sc6oi2i77.ap-southeast-1.rds.amazonaws.com:1433;databaseName=datn;encrypt=true;trustServerCertificate=true
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 8080

  - type: web
    name: datn-core-banking
    env: docker
    plan: free
    rootDir: core-banking-service
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:sqlserver://datn.ct4sc6oi2i77.ap-southeast-1.rds.amazonaws.com:1433;databaseName=core_banking;encrypt=true;trustServerCertificate=true
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 8081
      - key: DOCKER_HOST
        value: datn-kafka.onrender.com
      - key: REDIS_HOST
        value: datn-redis.onrender.com
      - key: VAULT_ADDR
        value: https://datn-vault.onrender.com

  - type: web
    name: datn-notification
    env: docker
    plan: free
    rootDir: notification-service
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 9821
      - key: DOCKER_HOST
        value: datn-kafka.onrender.com

  - type: redis
    name: datn-redis
    plan: free
    maxmemoryPolicy: allkeys-lru

  - type: web
    name: datn-kafka
    env: docker
    plan: free
    rootDir: kafka-service
    envVars:
      - key: KAFKA_CFG_NODE_ID
        value: 0
      - key: KAFKA_CFG_PROCESS_ROLES
        value: controller,broker
      - key: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
        value: 0@datn-kafka.onrender.com:9093
      - key: KAFKA_CFG_LISTENERS
        value: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - key: KAFKA_CFG_ADVERTISED_LISTENERS
        value: PLAINTEXT://datn-kafka.onrender.com:9092,EXTERNAL://datn-kafka.onrender.com:9094
      - key: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
        value: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - key: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
        value: CONTROLLER

  - type: web
    name: datn-vault
    env: docker
    plan: free
    rootDir: vault-service
    envVars:
      - key: VAULT_DEV_ROOT_TOKEN_ID
        value: myroot
      - key: VAULT_DEV_LISTEN_ADDRESS
        value: 0.0.0.0:8200 