services:
  - type: web
    name: datn-backend
    env: docker
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:sqlserver://34.124.165.193:1433;databaseName=datn;encrypt=true;trustServerCertificate=true
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 8080

  - type: web
    name: datn-core-banking
    env: docker
    plan: free
    region: oregon
    rootDir: core-banking-service
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/core-banking-service-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:sqlserver://34.124.165.193:1433;databaseName=core_banking;encrypt=true;trustServerCertificate=true
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 8081

  - type: web
    name: datn-notification
    env: docker
    plan: free
    region: oregon
    rootDir: notification-service
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/Notification-service-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 9821 