-- Migration file created on 19/06/2025 at 11:10:10.10 

-- amenities
ALTER TABLE amenities
ALTER COLUMN name NVARCHAR(100) NOT NULL;

ALTER TABLE amenities
ALTER COLUMN icon NVARCHAR(200) NULL;

-- hotel_room_variants
ALTER TABLE hotel_room_variants
ALTER COLUMN variant_name NVARCHAR(200) NOT NULL;

-- hotel_rooms
ALTER TABLE hotel_rooms
ALTER COLUMN room_type NVARCHAR(100) NULL;

ALTER TABLE hotel_rooms
ALTER COLUMN bed_type NVARCHAR(100) NULL;

ALTER TABLE hotel_rooms
ALTER COLUMN description NVARCHAR(MAX) NULL;

-- hotels
ALTER TABLE hotels
ALTER COLUMN name NVARCHAR(200) NOT NULL;

ALTER TABLE hotels
ALTER COLUMN address NVARCHAR(300) NULL;

ALTER TABLE hotels
ALTER COLUMN description NVARCHAR(MAX) NULL;

ALTER TABLE hotels
ALTER COLUMN email NVARCHAR(200) NULL;

ALTER TABLE hotels
ALTER COLUMN phone NVARCHAR(20) NULL;

