-- Migration file created on 19/06/2025 at 15:05:31.67 

INSERT INTO hotel_rooms (hotel_id, room_type, bed_type, description, max_adults, max_children, room_quantity, room_area, created_at, updated_at)
VALUES
(1, 'Deluxe Frontview Studio', '1 giường cỡ queen', null, 2, 1, 10, 21, GETDATE(), GETDATE()),
(1, 'Deluxe Backview Studio', '1 giường cỡ queen', null, 2, 1, 8, 22, GETDATE(), GETDATE()),
(1, 'Sofa 1 - Bedroom', '1 giường cỡ queen', null, 2, 1, 6, 24, GETDATE(), GETDATE());

INSERT INTO hotel_room_variants (room_id, variant_name, has_breakfast, cancellable, pay_at_hotel, price, status, created_at, updated_at)
VALUES
(1, 'Deluxe Frontview Studio - Non Refundable', 0, 1, 1, 1231456, 'available', GETDATE(), GETDATE()),
(1, 'Deluxe Frontview Studio - Non Refundable', 1, 0, 1, 1231456, 'available', GETDATE(), GETDATE()),
(1, 'Deluxe Frontview Studio - Standard Rate', 1, 1, 0, 1368284, 'available', GETDATE(), GETDATE()),
(2, 'Deluxe Backview Studio - Non Refundable', 1, 1, 0, 1237538, 'available', GETDATE(), GETDATE()),
(2, 'Deluxe Backview Studio - Standard Rate', 1, 1, 1, 1375042, 'available', GETDATE(), GETDATE()),
(3, 'Sofa 1-bedroom - Non Refundable', 1, 0, 0, 1396540, 'available', GETDATE(), GETDATE()),
(3, 'Sofa 1-bedroom - Standard Rate', 1, 0, 1, 1551710, 'available', GETDATE(), GETDATE()),
(3, 'Sofa 1-bedroom - Standard Rate', 0, 1, 1, 1551710, 'available', GETDATE(), GETDATE());

INSERT INTO amenities (name, icon) VALUES
('Wifi miễn phí', 'fas fa-wifi'),
('TV màn hình phẳng', 'fas fa-tv'),
('Điều hòa', 'fas fa-snowflake'),
('Máy sấy tóc', 'fas fa-wind'),
('Bồn tắm', 'fas fa-bath'),
('Tủ lạnh mini', 'fas fa-ice-cream'),
('Két sắt', 'fas fa-lock'),
('Ban công riêng', 'fas fa-door-open'),
('Dép đi trong phòng', 'fas fa-shoe-prints'),
('Bàn làm việc', 'fas fa-briefcase'),
('Ấm đun nước', 'fas fa-mug-hot'),
('Dịch vụ phòng', 'fas fa-concierge-bell'),
('Giấy vệ sinh miễn phí', 'fas fa-toilet-paper'),
('Cửa sổ cách âm', 'fas fa-volume-mute'),
('Thang máy', 'fas fa-elevator'),
('Bãi đỗ xe miễn phí', 'fas fa-parking'),
('Hồ bơi', 'fas fa-swimming-pool'),
('Phòng gym', 'fas fa-dumbbell'),
('Spa & massage', 'fas fa-spa'),
('Nhà hàng', 'fas fa-utensils'),
('Quầy bar', 'fas fa-cocktail'),
('Khu vực hút thuốc', 'fas fa-smoking'),
('Giường em bé', 'fas fa-baby'),
('Dịch vụ giặt ủi', 'fas fa-soap'),
('Máy pha cà phê', 'fas fa-coffee'),
('Bếp riêng', 'fas fa-fire-burner'),
('Lò vi sóng', 'fas fa-microphone-lines'),
('Máy lạnh trung tâm', 'fas fa-temperature-low'),
('Hệ thống sưởi', 'fas fa-thermometer-full'),
('Khăn tắm', 'fas fa-towel'),
('TV cáp', 'fas fa-satellite-dish'),
('Tivi thông minh (smart TV)', 'fas fa-chalkboard'),
('Tủ quần áo', 'fas fa-closet');

INSERT INTO hotel_room_amenities (room_id, amenity_id) VALUES
(1, 1),
(1, 3),
(1, 4),
(1, 5),
(1, 6),
(1, 8),
(1, 10),
(1, 12),
(1, 14),
(1, 17),
(2, 2),
(2, 3),
(2, 6),
(2, 7),
(2, 9),
(2, 11),
(2, 13),
(2, 15),
(2, 16),
(2, 18),
(3, 1),
(3, 2),
(3, 4),
(3, 5),
(3, 7),
(3, 10),
(3, 12),
(3, 14),
(3, 19),
(3, 20);
